### ISSUE TITLE
[RFE] Add docs to install the charts using the HelmChart CRD instead of the helm binaries

### ISSUE THREAD

**Issue by e-minguez** [suse-edge/charts#100]
Instead of using helm install, it would be nice to document examples on the charts on how to create the HelmChart objects directly if using rke2/k3s https://github.com/k3s-io/helm-controller

For example for metal3:

```
cat <<-EOF | ${KUBECTL} apply -f -
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ${METAL3CHART}
  namespace: kube-system
spec:
  repo: ${METAL3REPOURL}
  chart: ${METAL3CHART}
  targetNamespace: ${METAL3NAMESPACE}
  version: ${METAL3VERSION}
  createNamespace: true
  set:
    global.ironicIP: ${IRONICIP}
  valuesContent: |-
${VALUES}
EOF
```
