### ISSUE TITLE
Shall we use Neuvector 5.3.0?

### ISSUE THREAD

**Issue by e-minguez** [suse-edge/charts#109]
https://github.com/suse-edge/charts/blob/48dcba2d5ba553b8d23ee21384558de325f15e4d/charts/neuvector-core/2.6.6/values.yaml#L8

**Comment by e-minguez** [comment]
Also a diff from the original one https://github.com/neuvector/neuvector-helm/blob/master/charts/core/values.yaml with the one here just bring these changes:

```
controller:
  replicas: 1
  ranchersso:
    enabled: true
manager:
  enabled: false
cve:
  scanner:
    enabled: false
    replicas: 1
k3s:
  enabled: true
crdwebhook:
  enabled: false
```

Shall we just minify ours and refer to the original one for more elaborated changes?
