### ISSUE TITLE
Metal3 enable debug access to Ironic CLI

### ISSUE THREAD

**Issue by hardys** [suse-edge/charts#121]
The `baremetal` Ironic CLI is included in the Ironic container image, but it's currently inconvenient to use since you have to create a configuration file like:

```
cat /tmp/clouds.yaml 
clouds:
  metal3:
    auth_type: "http_basic"
    endpoint: "https://127.0.0.1:6385"
    baremetal_introspection_endpoint_override: "https://127.0.0.1:5050"
    verify: False
    auth:
      username: "ironic"
      password: "PASSWORD"

```

Where PASSWORD is retrieved from the ironic-basic-auth secret e.g

```
kubectl get secret -n metal3-system ironic-basic-auth -o json  | jq -r .data.password | base64 -d
```

Then if you export OS_CLOUD=metal3 it's possible to use the `baremetal` command inside the Ironic container.

It would be better if we generated this config inside the container, given that all the necessary information already exists there.
