### ISSUE TITLE
More thorough kubevirt example

### ISSUE THREAD

**Issue by brandonros** [suse-edge/charts#147]
First off, thanks for trying to put a chart on this! I'm guessing there isn't an official one as per https://github.com/kubevirt/kubevirt/issues/8347 because it is very hard to do or complex or something (I know very little about Kubevirt, just something I read on a blog post and wanted to try)

```yaml
kind: Namespace
apiVersion: v1
metadata:
  name: kubevirt
  labels:
    name: kubevirt
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kubevirt
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: kubevirt
    server: https://kubernetes.default.svc
  orphanedResources:
    warn: false
  sourceRepos:
  - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubevirt
  namespace: argocd
spec:
  syncPolicy:
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 1
        maxDuration: 10m
    syncOptions:
    - ServerSideApply=true
  destination:
    server: https://kubernetes.default.svc
    namespace: kubevirt
  project: kubevirt
  source:
    repoURL: https://github.com/suse-edge/charts.git
    targetRevision: 99235e25388eb45a94235d4baea6c232a6249d44
    path: ./charts/kubevirt/0.3.1/
```

I was trying to deploy this through ArgoCD and it just kind of times out.

I wanted to start this GitHub issue to get guidance on... should I not be trying to do it this way? Let me try to get better errors and update this issue. Apologies if this is the wrong place to post, just... can't quite figure out how to get this to work. It doesn't seem as simple as "just install it/apply it and you're good". Not sure if some default configuration on how to deploy like a Debian12 virtual machine would help others less familiar. I agree, slightly out of scope.

**Comment by brandonros** [comment]
`kubevirt-crd-upgrade` job seems to CrashLoopBackoff with

```
Error from server (Forbidden): error when creating "/etc/manifests/crd.yaml": customresourcedefinitions.apiextensions.k8s.io is forbidden: User "system:serviceaccount:kubevirt:kubevirt-crd-upgrade" cannot create resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope
```

**Comment by atanasdinov** [comment]
Are you able to grab Argo logs? I'm not sure what it is doing under the hood but I'm unable to replicate this even with installing the chart via the `upgrade` command:
```
helm upgrade kubevirt charts/kubevirt/0.3.1 -n kubevirt -i --create-namespace 
```

**Comment by brandonros** [comment]
Would you have expected I had to add this?

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubevirt-crd-manager
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubevirt-crd-manager-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubevirt-crd-manager
subjects:
- kind: ServiceAccount
  name: kubevirt-crd-upgrade
  namespace: kubevirt
```
