### ISSUE TITLE
Kubevirt and CDI chart names mismatch when used as a dependency chart

### ISSUE THREAD

**Issue by hickersonj** [suse-edge/charts#190]
**Scenario**
While lint'ing and deploying kubevirt referenced as a dependency chart it fails due to the chart name not matching the Chart.yaml chart name. According to https://helm.sh/docs/helm/helm_dependency/#helm the chart name should match. I.e. `kubevirt-chart` should be `kubevirt`. This is also the case for `cdi-chart` it should be `cdi`.

**Steps to reproduce**
Create a parent `Chart.yaml` file with:

```yaml
apiVersion: v2
name: parent-kubevirt
description: The parent Helm chart for kubevirt

type: application

version: 0.1.0

dependencies:
  - name: kubevirt-chart
    version: "0.3.0"
    repository: "oci://registry.suse.com/edge"
```
Lint the chart and it will fail. It also fails when deploying the helm chart after one builds the dependency. This should deploy without requiring the `--dependency-update` flag

**Expected Result**
The helm lint command should pass.

**Actual Result**
Error for lint
```
helm lint parent-kubevirt/
==> Linting parent-kubevirt/
[INFO] Chart.yaml: icon is recommended
[ERROR] /home/user/helm/parent-kubevirt: chart metadata is missing these dependencies: kubevirt,kubevirt
[WARNING] /home/user/helm/parent-kubevirt: chart directory is missing these dependencies: kubevirt-chart

Error: 1 chart(s) linted, 1 chart(s) failed
```

Deployment error
```
helm install kubevirt ./parent-kubevirt --values parent-kubevirt/values.yaml --create-namespace
Error: INSTALLATION FAILED: An error occurred while checking for chart dependencies. You may need to run `helm dependency build` to fetch missing dependencies: found in Chart.yaml, but missing in charts/ directory: kubevirt-chart
```

Note, the deployment error can be resolved with the `--dependency-update` flag, but if one runs `helm dependency build parent-kubevirt` it should not require the flag later.
