### ISSUE TITLE
kubevirt unit is failing in sylva due to some security loopholes

### ISSUE THREAD

**Issue by manik9910** [suse-edge/charts#50]
Helm chart used: https://github.com/suse-edge/charts/tree/main/charts/kubevirt/0.1.0
Sylva: https://gitlab.com/sylva-projects/sylva-core/
Sylva Env: rke2-capo, rke2-capo-capm3, rke2-capm3

Issues created in Sylva:

- https://gitlab.com/sylva-projects/sylva-core/-/issues/648
- https://gitlab.com/sylva-projects/sylva-core/-/issues/647

Kubevirt unit is getting installed in Sylva: https://gitlab.com/sylva-projects/sylva-core/-/blob/main/charts/sylva-units/values.yaml?ref_type=heads#L302-L308

It is failing with several reasons, majorly the security loopholes of helm chart

1. Sylva's kyverno policy is expecting that resources should not be create in default namespace but most of the resources from helm chart get created under default namespace: 

- https://github.com/suse-edge/charts/blob/main/charts/kubevirt/0.1.0/templates/kubevirt-crd-upgrade.yaml
- https://github.com/suse-edge/charts/blob/main/charts/kubevirt/0.1.0/templates/kubevirt-crd-uninstall.yaml

Error:
```
disallow-default-namespace:
  validate-podcontroller-namespace: 'validation error: Using ''default'' namespace
    is not allowed for pod controllers. rule validate-podcontroller-namespace failed
    at path /metadata/namespace/'
```

2. There is need to set seccomp under some of resources like jobs(not sure about others) under kubevirt-crd-upgrade.yaml and kubevirt-crd-uninstall.yaml. But I am not able to do so via kustomize patch in sylva as it seems like helm hooks doesn't allow it.

For example:
```
                  template:
                    metadata:
                      name: kubevirt-crd-upgrader
                    spec:
                      serviceAccountName: kubevirt-crd-upgrader
                      restartPolicy: OnFailure
                      containers:
                        - name: kubevirt-crd-upgrader
                          securityContext:
                            seccompProfile:
                              type: RuntimeDefault
                            runAsNonRoot: true
                            allowPrivilegeEscalation: false
                            capabilities:
                              drop:
                              - ALL
```

3. Mainly I am getting the below error in `kubectl describe helmrelease kubevirt -n workload-cluster` which might be due to above two issues.

```
Last Helm logs:

resetting values to the chart's original version
performing update for kubevirt
creating upgraded release for kubevirt
creating 1 resource(s)
warning: Upgrade "kubevirt" failed: pre-upgrade hooks failed: warning: Hook pre-upgrade kubevirt/templates/kubevirt-crd-upgrade.yaml failed: 1 error occurred:
  * configmaps "kubevirt-crd-manifest" already exists
```

4. It's also observed that, at first kubevirt unit gets created successfully but it fails in some mins after reconciliation.
As a result of which, VMs created after kubevirt unit, fail in the absence of seccomp. 

Issue created in Sylva: https://gitlab.com/sylva-projects/sylva-core/-/issues/647

But this might not be directly related to helm chart. It may be required to fix in VM templates
